# Site settings
title: Gyan Mishra
#twitter_username: rob_hinds
name: Gyan Mishra

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 #- title: Blog
  # url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/mishra-gyan
 #- title: StackOverflow
 #  url: https://stackoverflow.com/users/258813/rhinds
 #- title: DZone
 #  url: https://dzone.com/users/899489/rhinds.html
 - linketitle: LinkedIn
   url: https://www.linkedin.com/in/mishragyan/
 #- title: Food
  # url: https://www.robbishfood.com/

#Any buzzword skills you want to include
skills:
 - Java
 - Product management
 - API design
 - SQL
 - REST
 - Pega
 - Technical Architecture
 - Machine learning
 - Microservices

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Executive Director
   start: 2006
   end: Ongoing
   employer: Morgan Stanley
   description: Oversee, Support and manage Tech leads for extending Morgan Stanley’s Institutional Client KYC and Client Onboarding platform.
 - title: Executive Director
   start: 2016
   end: 2018
   employer: Morgan Stanley
   description: Led the global team of 30 developers and regional leads in building and integrating the Client allocation system for equity and FID products
 - title: Executive Director
   start: 2014
   end: 2016
   employer: Morgan Stanley (Bangalore)
   description: Provided local leadership to setup a new team in Bangalore and expanded the foot print of the super department in the region by participating in campus and lateral hiring events.
 - title: Associate/VP/ED
   start: 2007
   end: 2016
   employer: Morgan Stanley
   description: Worked as a team lead managing the NY and Montreal team of 6 for Securities Allocation System in Core equity.
 - title: Senior Associate
   start: 2006
   end: 2007
   employer: Morgan Stanley (Mumbai)
   description: Worked as a developer in various components within Securities Allocation System.
 - title: Software Engineer
   start: 2004
   end: 2006
   employer: SmartStream Technologies (Mumbai)
   description: Worked as a developer in one of the Leading product from SmartStream Technologies, TLM PA (Process Automation).
 - title: Systems Engineer
   start: 2002
   end: 2004
   employer: NucSoft Ltd (Mumbai)
   description: Worked as a developer for OrbiONE ALM product developer for Polaros (Formerly Orbitech) for asset-liability management of any financial institute.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2002
   subject: Computer Science
   school: University of Mumbai
 - level: Master of Computer Applications(MCA)
   date: 2005
   subject: Computer Applications
   school: IGNOU

#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/specializations/algorithms
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
# github:
#  - robhinds/robhinds.github.io
#  - robhinds/ScaLambda
#  - robhinds/opinionated-akka-http
#  - robhinds/food2vec
#  - robhinds/microservices
#  - robhinds/spring-social-geeklist
#  - robhinds/spring-social-stackoverflow
#  - robhinds/genotype
#  - robhinds/footweets
#  - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am an engineer manager with 18 years experience working in technology. I have primarily worked in Banking and Financial institions primarily in middle office, regulatory and compliance division. <br/><br/>
  I am highly collanborative and innovative in building highly scalable distributed applications with a passion for first-in-class engineering principles, clean extensible interfaces,, code simplicity, system maintainability and testability. <br/><br/>
  I am well versed in building consensus, thinking big picture and handling ambiguity. I am also an empathetic leader who believes in the immense potential of investing in people and teamwork. <br/><br/>
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Client Onboarding and KYC</strong>: In my current role Responsible for overall technical design and delivery of renovated platform to achieve Sustainable state program for Data and Document refresh for clients in scope for KYC. Key goal of the project were to meet a commitment to Federal Reserve bank to achieve timely completion of KYC regulations.<br/><br/>
   
